### ISSUE TITLE
"Digest::SHA1" obsolete/deprecated, please replace with "Digest::SHA"

### ISSUE THREAD

**Issue by pms967** [ericvaandering/DocDB#10]
Subj. says it all: "Digest::SHA1" is no longer included in modern distributions. Please change to "Digest::SHA".

https://duckduckgo.com/?q=Digest%3A%3ASHA1+has+been+deprecated%2Fremoved+in+Debian+and+Ubuntu

P.S.:
grep -ir 'Digest::SHA' docdb/
docdb/cgi/EmailSecurity.pm:  use Digest::SHA1 qw(sha1_hex);
docdb/scripts/CheckModules:               "Digest::SHA1",

**Comment by ericvaandering** [comment]
Fixed by #15 which will be in next release
