### ISSUE TITLE
Wrong folder reference in DocDBGlobals.pm

### ISSUE THREAD

**Issue by iniOr** [ericvaandering/DocDB#102]
In the DocDBGlobals.pm there are some reference to a `Static` folder, however this folder name seems to have been updated in the latest version to `html`, this is preventing js and css from loading and create 404 errors in httpd.

Source :

```
286 unless ($CSSDirectory && $CSSURLPath) {
287 $CSSDirectory = $file_root."/Static/css";
288 $CSSURLPath = $web_root."/Static/css";
289 }
290
291 unless ($JSDirectory && $JSURLPath) {
292 $JSDirectory = $file_root."/Static/js";
293 $JSURLPath = $web_root."/Static/js";
294 }
295
296 unless ($ImgDirectory && $ImgURLPath) {
297 $ImgDirectory = $file_root."/Static/img";
298 $ImgURLPath = $web_root."/Static/img";
```

Working modification:

```
286 unless ($CSSDirectory && $CSSURLPath) {
287 $CSSDirectory = $file_root."/html/css";
288 $CSSURLPath = $web_root."/html/css";
289 }
290
291 unless ($JSDirectory && $JSURLPath) {
292 $JSDirectory = $file_root."/html/js";
293 $JSURLPath = $web_root."/html/js";
294 }
295
296 unless ($ImgDirectory && $ImgURLPath) {
297 $ImgDirectory = $file_root."/html/img";
298 $ImgURLPath = $web_root."/html/img";
299 }
```

**Comment by ericvaandering** [comment]
In the GH repo, that's true. The intention is that you install what's in those directories INTO a directory called Static. But if this modification works better for you, I'd encourage you to keep using it. It would, however, break every existing installation.

**Comment by pms967** [comment]
> In the GH repo, that's true. The intention is that you install what's in those directories INTO a directory called Static. But if this modification works better for you, I'd encourage you to keep using it. It would, however, break every existing installation.

then why not changing the GH repo structure to be consistent with existing "standard" installations?
