### ISSUE TITLE
wrong HTTP status code if requested document does not exist

### ISSUE THREAD

**Issue by sbailey** [ericvaandering/DocDB#11]
DocDB 8.8.5 returns HTTP status code 200 (Success) even if the requested file does not exist, e.g.

https://docdb.org/cgi-bin/private/RetrieveFile?docid=347;filename=blat;version=11

It should return 404 Not Found.

**Comment by ericvaandering** [comment]
This one will not be fixed.

**Comment by weaverba137** [comment]
Maybe the original question wasn't phrased properly.  Perhaps we should just be using a different version?

**Comment by ericvaandering** [comment]
No, sorry, this is a "feature" unfortunately.
