### ISSUE TITLE
Able to create account with special characters in it

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#51]
We are able to create personal accounts that have
non-alphanumeric chars in them.
  (so I can create/impersonate [an SSO login])
  Was able to do this in both fnalsso and 889.
  
Apparently 7dff92fb237fb6f5d9b78399901ce370c27da956 did not work.

**Comment by ericvaandering** [comment]
Cannot reproduce this. A short snippet 
```
#! /usr/bin/env perl

$UserName = "SSO:ewv@fnal.gov";

if ($UserName !~ /^[a-zA-Z][a-zA-Z0-9_\.\-\@]+$/) {
  print "Your username may not contain any special characters except dash, period, \@, or underscore.";
}
```
prints the correct thing and EmailCreate should refuse to do anything if ErrorStack exists.

**Comment by ericvaandering** [comment]
If this is still a problem, I'll need a test bed where I can debug it.

**Comment by ericvaandering** [comment]
Fixed in the latest FNAL_sso

**Comment by lauramengel** [comment]
Hi. I checked this in fnal_sso and it is fixed (with one point of info).

As we want, I was not able to create a username with
- colon
- slash
- special chars

As we want, I was a able to create an account with legal chars:
- l_m-m.1M@foo.com

 I'll send the point of info screengrab to your email.

**Comment by ericvaandering** [comment]
Not ideal, but I'll close it. I don't think its a security issue.
