### ISSUE TITLE
In SSO version, verifying or making a change to a personal   account does not send email

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#52]
In SSO version, verifying or making a change to a personal
  account does not send email to a user or docdb admins.
  Does send email for same in the certificate version.
  I think we want the user to be notified when an admin
  has granted them access after they applied for access.

  Maybe need to add "$UserValidation eq "FNALSSO"" in "if" to
  some more places that have "$UserValidation eq "certificate""
  such as in EmailAdminister and/or EmailAdministerForm for
  some cases such as when $MailInstalled. There may be other places.

**Comment by ericvaandering** [comment]
Fixed by #25 in FNAL_sso branch

**Comment by lauramengel** [comment]
Confirmed in SSO version, both verifying or making a change to a personal account does send email now (to user and to admin email address). Closing issue.
