### ISSUE TITLE
Change message is scary

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#53]
[High priority because there is a very old ticket for this]
  Current message is: "An administrator has made a change to your
  XYZ DocDB DocDB account. If you think this was done in error,
  please contact blah immediately."

  From ticket: "Several people interpreted the automatically
  generated email as a security breach and we spent time
  investigating."

  This is for personal account "Modify" action only.
  Should not affect "Transfer" or "Delete" messages.
  Same behavior as before if Verify checkbox not checked.
  (No email sent.)

  Old text (Keep if Verify was 0 and Verify checkbox checked):
  An administrator has approved the request for <username> for
  access to <instancename> DocDB. If you did not request access
  to <instancename> DocDB, please contact <adminemail> immediately.

  New generic text (Use if Verify was 1 and Verify checkbox checked)
  An administrator has made a change to your <instancename>
  DocDB account (such as changing group memberships). If you
  think this was done in error or have questions,
  please contact <adminemail>.

**Comment by ericvaandering** [comment]
This was already changed once for this release in https://github.com/ericvaandering/DocDB/commit/bfb4565c97808aecea9e643cdf933bfa292b82f2

**Comment by ericvaandering** [comment]
I don't know the previous value of verified at this point, so I'll make a generic message covering both cases.

**Comment by lauramengel** [comment]
Confirmed reworded message is sent on account verification and changes.
Closing ticket.
