### ISSUE TITLE
Problems using undefined database handles

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#56]
Several places:

Administer Document Type shows "internal server error"
  for incorrect username/password. (unknown where)

ExternalDocDBAdministerForm: If put in incorrect
  username/password, doesn't display same error message
  as the others (to say that should check that they have
  the right admin username and password). Says instead:
  "Can't call method "prepare" without a package or
  object reference at SecuritySQL.pm line 32."
  (or line 37 or 41)

SSO TopicAdminister, EventAdminister:
  When put in incorrect username/password, has the desired
  "incorrect username/password" message. But after that
  still shows "Software Error: Can't call method "prepare"
  without a package or object reference at FNALSSOUtilities.pm
  line 85." For the other admin functions, it shows the desired
  "incorrect username/password" instead of the "software error".)

**Comment by ericvaandering** [comment]
These issues are only fixed on the SSO branch. Some of the line numbers imply you are testing this in the 889 branch only.

The last paragraph is kind of unclear what's going on. I tweaked things a bit so that I hope it is better/fixed, but I can't see the problem.

**Comment by ericvaandering** [comment]
So please retest with the latest SSO branch and see if there are still problems.

**Comment by lauramengel** [comment]
The Admin Doc Type issues is from DocTypeAdminister:
- Administer DocDB
- Administer authors, institutions, types and journals
- 3rd panel "Administer Document Types"
- Any of the 3 actions, fill in fields as desired (or not)
- Put in an incorrect username and password
- Click on "Change Document Type Info"
Result is "Internal Server Error".

I believe I tested the issues in the fnalsso version (not 889),
but I'll try it again with the new fnalsso version I got today.

**Comment by lauramengel** [comment]
Hi. I did a git pull this morning on DocDB fnal sso version and
re-tested with that and got the same behavior for all 3 items
as I originally posted (for item #56 RE undefined DB handles).

Instructions for reproducing the Administer Document Type
"internal server error" are in the comment above for Git #56.

**Comment by ericvaandering** [comment]
These should be fixed in the latest FNAL_SSO branch. There were a couple of subtle issues
