### ISSUE TITLE
Misleading error message on adding signers

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#57]
For error message for adding signers to a document, if no
  unique match found or account is not allowed to sign documents,
  next sentence says "Please go back and try again." However,
  trying again won't help. They need to contact their DocDB
  admins email address to request admins modify the needed
  personal accounts so that cansign can be added to the needed
  account or cansign can be removed from unneeded accounts
  (with the same first and last name) so a given user has
  cansign enabled for 1 (but not more than 1 account).

**Comment by lauramengel** [comment]
Confirmed this is addressed. Desired error message shows if
chosen signer cannot sign or there is more than one account
with cansign for the same name, and tells the user to contact
an admin to fix this.  Closing issue.
