### ISSUE TITLE
Signature chooser shows unverified account

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#60]
A personal account that has cansign, but is not verified,
  can be chosen in signoff chooser (and submitting doc works).
  Ex: create document, update document, update metadata
  Consider not showing personal account in signoff chooser
  unless it is both verified and cansign?

**Comment by lauramengel** [comment]
Thanks. This is fixed. Tried for verified/cansign users with:
No/No, No/Yes, Yes/No, Yes/Yes
and only the Yes/Yes was included in the signoff chooser.

Closing issue.
