### ISSUE TITLE
Special characters are being displayed as HEX

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#61]
Two places:

On DocumentAddForm, Submitter and Author fields
  display hexcode instead of char like apostrophe.
  (Our dept. head has an apostrophe in his name O'Connell.)
  This also means if you type "O'C" into the author/submitter
  field, O'Connell will not be found because it shows Ox27Connell.
  Apostrophe displays correctly on ListAuthors, AdministerForm
  (admin authors) page and author list (Moderators) to select
  for making a new event.

On CertificateApplyForm, group names in long descrition
  are displayed with hexcodes instead of chars like "&".
  This affects a number of ES&H groups (ES&#x26; for ES&H).
  The group names / long description are displayed fine
  on other pages such as GroupAdministerForm.

**Comment by ericvaandering** [comment]
In the first instance is this is the scrollable author or the JS chooser?

**Comment by ericvaandering** [comment]
![screenshot 2018-05-16 14 04 30](https://user-images.githubusercontent.com/1672366/40138449-4d764f06-5912-11e8-9afa-9da59dba00f6.png)

Not clear the problem is not on the frontend.

**Comment by lauramengel** [comment]
Hi. Yes, it seems that O'Boyle or whatever authors were added years
and years ago are ok. But if I add a new author now (I tried O'Malley)
then that has the x27 problem you showed in the image you just loaded).
Perhaps it's in any apostrophed etc authors added after the special char
translation you did a few years back.

**Comment by ericvaandering** [comment]
OK, the second one is fixed too. I *think* maybe the underlying library changed and my sanitization of HTML before sticking stuff in the lists is no longer needed. I hope that's it and you don't start seeing script popups and such coming back.

We might also find more places this needs to be undone.

**Comment by lauramengel** [comment]
Hi. Both the special chars in authors and groups are fixed on all author and group lists
including certapply page. Also made a new author with special char on both user page
and admin page and the special char (in this case apostrophe) was displayed fine.

Closing issue.
