### ISSUE TITLE
Software error when applied for certificate access

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#69]
Using FNALSSO, branch applied for access for new certificate and got error:
Can't use an undefined value as a symbol reference at /web/sites/d/docdbdev.fnal.gov/cgi-bin/sites/ESH_Cert_Req/UserAccessApply line 154.

Though it said "An e-mail has been sent to the administrators and a confirmation e-mail has been sent to you.", no email was sent to either (perhaps because of the error).

The certficate account requesting access was not on the personal account list before applying.
(though it was on the personal accounts list earlier and deleted, if that matters).

The certificate account was successfully added to the personal accounts list as usual after applying.
(with Verify No, cansign No and the requested groups listed)

**Comment by ericvaandering** [comment]
I just added a patch for this to the latest FNAL_SSO. It's a problem I corrected on the SSOAccessApply but not certificate....

**Comment by lauramengel** [comment]
This is fixed. Closing issue.
- No software issue now.
- Emails sent to user and admins to add access.
