### ISSUE TITLE
personal account transfer does not send email, text rewording

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#70]
I did a personal account transfer in the an SSO version DocDB, and no email was
sent to the email address of the old account, new account or admin email address.
Past notification email had the subject: "DocDB account for John Smith updated".

This sounds similar to #52 ... maybe need to add "$UserValidation eq "FNALSSO"" in "if" to
some more places that have "$UserValidation eq "certificate"" to decide whether to email?

Also, the wording may need to be changed now that we have SSO accounts besides
certificate accounts, to reduce confusion. Looks like the message will say:
"An administrator has transferred permissions from the certificate
$EmailUser{$EmailUserID}{Name} to the new certificate
$EmailUser{$NewCertID}{Name} for access to $Project DocDB
If you think this was done in error,
please contact $DBWebMasterEmail immediately."

I think the "immediately is ok for this case. What may be confusing to users and admins
is that it says "from the certificate ... to the new certificate", whether they are transferring
between 2 SSO accounts, 2 cert accounts or 1 of each.

Fancy fix would be to say "single sign-on account" if the string starts with SSO:
and "certificate account" if the string starts with "/".

Less fancy fix would be to say "account" instead of "certificate".
However then if a person's SSO account is transferred to their CILogin Fnal
or visa versa (which will be our most frequent cases), the message will say:
"An administrator has transferred permissions from the account
Laura Mengel to the new account Laura Mengel ..."
which does not make it clear what action was actually done.

We have the same problem transferring from cert to cert,
but that is mitigated because most (but not all) certs have
a slightly different CN (EX: KCA has middle initial, Cilogon fnal
does not have middle initial, other CILogin certs and other certs include hash,
so most of the time the admin can look back and determine what
was transferred to what. But the SSO names and CILogon Fermi names
are the same.

**Comment by ericvaandering** [comment]
What if we dropped "account/certificate" entirely and used the Username instead of the Name which should then read something like

An admin has transferred from /DN=blah/CN=Eric Vaandering/etc to SSO:ewv@FNAL.gov?

**Comment by ericvaandering** [comment]
The subject line of the e-mail would still have the "Name"

**Comment by ericvaandering** [comment]
DN should not be considered a secret, as far as I know. We expose them to many tools on CMS and on the web.

**Comment by lauramengel** [comment]
On 5/30/18 4:41 PM, Eric Vaandering wrote:
> The subject line of the e-mail would still have the "Name"

Sounds good.

> DN should not be considered a secret, as far as I know. We expose them to many tools on CMS and on the web.

Ok, and the SSO:UID is definitely not a secret since you can look it up online.
So go ahead and change this, it will make it a lot clearer for the user
and admin to look back and see what was switched from and to.

I think we're at something like this for the transfer action message:

An administrator has transferred permissions and settings from the account <USERNAME1>
to the account <USERNAME2> for access to $Project DocDB.

So while we're at it, we might as well make the last sentence the same as for "modify":

EmailAdminister- $Body .= "If you think this was done in error or have questions, ";
EmailAdminister- $Body .= "please contact $DBWebMasterEmail.";

**Comment by ericvaandering** [comment]
Subject and message now read:

```
$Subject = "DocDB account for [Full name] updated";
      
$Body = "An administrator has transferred permissions from 
account [DN or SSO:username] to 
account [DN or SSO:username]  for access to [Project] DocDB. 
If you think this was done in error or have questions, please contact [admin e-mail]."
``` 
And should be sent now (logic also changed)

**Comment by lauramengel** [comment]
This is fixed. Closing issue.
- Transfer Action in SSO version DocDB sends email now.
- Text is reworded so it's clear what got transferred to what.
