### ISSUE TITLE
request to add check for $Preferences{Security}{UseCertGroupsForSSO}

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#72]
In FNALSSOUtilities.pm, in sub FetchSecurityGroupsForFSSO
can you add $Preferences{Security}{UseCertGroupsForSSO}
to this check:

From:
\# And finally from their cert as well if we are not copying
  if (!$Preferences{Security}{TransferCertToSSO}) {

To:
\# And finally from their cert as well if we are not transferring
\# and $Preferences{Security}{UseCertGroupsForSSO} is true.
 if (!$Preferences{Security}{TransferCertToSSO} && $Preferences{Security}{UseCertGroupsForSSO}) {

**Comment by ericvaandering** [comment]
Fixed. Will be in the same commit that fixes #58, so wait until you see a message there to pull and test

**Comment by lauramengel** [comment]
fixed my formatting in my first post here too since the pound sign for comment
did not do what I expected.

**Comment by ericvaandering** [comment]
Fixed. Please test

**Comment by ericvaandering** [comment]
@lauramengel this is the last issue in the queue.

**Comment by lauramengel** [comment]
This is fixed. Closing issue.
- SSO does not inherit cert groups if not transferring and UseCertGroupsForSSO is false
- SSO doe inherit cert groups if not transferring and UseCertGroupsForSSO is true.
