### ISSUE TITLE
public link on document page versions area, even when no public version of doc

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#74]
On a document, in the box on the right that lists versions,
under "Quick Links" there is a link to "Public Version" even
if there is not a public version of that document. If you click
on it, you get an error
"There were fatal errors processing your request:
You do not have permission to view this document (or it does not exist)."

**Comment by ericvaandering** [comment]
Want to try the branch remove_public_link? That should fix it, but this branch can't be used with SSO, so it's not so easy for me to test.

Eric

**Comment by lauramengel** [comment]
Ok. The public link does not show up if all versions of the doc are private.
The public link does show up and work if all versions of the doc are public.
The public link goes to the latest version of the doc.

However, if a doc has version 1 public and version 2 private,
the public link does not show up in the "Quick Links" area
on either version 1 or 2.

Maybe this case wasn't meant to show the public link,
in which case we can close this (since no error to user anymore).

If this case was meant to show the link to the latest public version,
we could move it to 8.8.10 or go another round, your choice.
I do not think this is a show stopper.

**Comment by ericvaandering** [comment]
The current behavior appears to be the original intent (there was an actual bug). Showing a link to the most recent public version seems like a nice enhancement to consider for 8.8.10

**Comment by lauramengel** [comment]
Ok. I will close this then and put in my notes this could be an enhancement for later.

So then this just needs to get into the final code we'll use.

**Comment by lauramengel** [comment]
I meant the fix (not the enhancement) just needs to get in the final code
we'll use for this release.
