### ISSUE TITLE
request case insensitive matching of SSO_FNAL_GROUPS  items with LDAP->DocDB group mapping

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#76]
We request group names in SSO_FNAL_GROUPS and group names
 in the SSO groupmap files that have our LDAP->DocDB group mapping
be compared case insensitively.

The authentication group recently told me:
"According to the LDAP protocol request for comments (RFCs),
distinguished names should be compared case-insensitively."

**Comment by ericvaandering** [comment]
What if we said that the dictionary $SsoGroupMap defined in ProjectGlobals HAD to have the various keys defined as lower case? There's not really a place where I can change both sides of the comparison to lower case, so I would have to re-write a 2nd dictionary (temporary) with lower case keys.

**Comment by ericvaandering** [comment]
Latest FNAL_SSO has this.

**Comment by lauramengel** [comment]
This is working with our group map with all lower case in the DN an no spaces around the equals.
Also works fine if there are spaces in the CN or OU and if DocDB groups specified included
mixed case, slash, space, or underscore.

Closing request.
