### ISSUE TITLE
Remove signature button shown for user after removed "cansign" from account

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#78]
Consider adding check to not show "sign document" or "remove signature" buttons if
the designated account either (or both)
- does not have cansign permissions
- is not verified

**Comment by ericvaandering** [comment]
Want to try it now? That and #77 should be fixed in the latest SSO branch.

The sign button should only appear if it's the correct user viewing it, so did you test the case where it is assigned to a user that doesn't have signature authority? From the title, I'm guessing yes.

**Comment by lauramengel** [comment]
> did you test the case where it is assigned to a user that doesn't
> have signature authority? From the title, I'm guessing yes.

Yes. I needed to remove sign privileges for testing something else
and then saw the remove button was still there.

**Comment by lauramengel** [comment]
This is fixed. Closing issue.
Add and remove signature buttons appear if the designated signer has cansign.
Neither button appears if the designated signer does not have cansign.
