### ISSUE TITLE
typo in Security.pm line 234 (not able to update docs, update metadat, add files)

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#87]
When I am viewing a document, if I click on any of these 3 links:
- Update Document
- Update Metadata
- Add files

I get this error:   
Not an ARRAY reference at Security.pm line 234.

The other two links did not show this problem:
- Create similar
- Watch document

**Comment by lauramengel** [comment]
Looks like the period just needs to be changed to a comma in Security.pm line 234:

   push @DebugStack. "Checking on ability to preserve docs for mode $Mode";

**Comment by ericvaandering** [comment]
Yes. Sorry.

**Comment by ericvaandering** [comment]
Done

**Comment by lauramengel** [comment]
This is fixed. I am able to click on  update doc, update meta-data and add files again.
