### ISSUE TITLE
Switch ops over to 889 branch, tell me when to prepare final release

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#89]
The FNAL_sso branch is now merged into 8_8_9_br, so all future patches will be on that branch only. You should be running 8_8_9_br from now on.

When you are truly satisfied and before the release date, let me know and we will close out #21 by merging all this into master.

**Comment by lauramengel** [comment]
I have tested a variety of actions in all 4 versions (pub/priv/cert/sso)
and have not seen issues (knock wood).

So please go ahead and finalize this release and tell me when it's ready.

- turned off debugging everywhere and saw no stray messages
- turned off SSO URL everywhere and saw no update/sign/access/groups emails with it
- did not select preserve for all file actions (create, update metadata, update doc, add files)
  and retest showed same as before (updates happened, signatures are triggered (as wanted)

**Comment by ericvaandering** [comment]
Ok, you can pick up 8.8.9 from the master branch, the 8.8.9 tag or as a zip file from https://github.com/ericvaandering/DocDB/releases
