### ISSUE TITLE
CreateDatabase: "TYPE=" incompatible with latest mysql

### ISSUE THREAD

**Issue by pms967** [ericvaandering/DocDB#9]
On CreateDatabase.SQL file the use of  "TYPE=..." was deprecated since a long time and no longer compatible wit new versions of mysql (such as 5.7, which is the on distributed with Ubuntu 16.04LTS).

Please replace it with  "ENGINE=..."

**Comment by ericvaandering** [comment]
Thank you. Will do

**Comment by dback** [comment]
I fixed this manually on my copy after extracting. The 'latest' zip at https://sourceforge.net/projects/docdb-v/ still contains the bad syntax version. Thanks for fixing it here in git.

**Comment by ericvaandering** [comment]
Fixed by #17 which is working its way into release
