### ISSUE TITLE
Authors with no last name or no first name break author selection (js search method)

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#90]
@lauramengel is this the right description? We have a suggested patch to the Javascript which will fix this.

**Comment by lauramengel** [comment]
Hi. I have looked into this more and determined all DocDBs
that had an author selection issue had at least one author
that had only a first name (with no last name) or only a last name
with no first name. I see 3 things to address:

a) Allow "Cher" authors with a single name (only first, only last).

Several experimenters expect this to work as they have an author name for inside or outside the collaboration which is 1 word. Examples: "Non-Collaborator",  "OTHER-INFN",  "SciBar Collaboration", "Non-NOvA Author",  "Non-MINOS-Author", "Entire Collaboration", 

From Mohammed Yahya: 
> The code in the file "*AutherSearch.js*" needs simple checking in the
> function "matchSubset_start" to find if the item is null or not, so I
> suggest to add this code in the line 73 from the file *AuthorSearch.js*:
> *If( s=== undefined || s=== null)***

Also see 2nd screen picture from Mohammed and generally
review code to see if any other changes are needed to allow
firstname or lastname (but not both) to be empty.

![image001](https://user-images.githubusercontent.com/39315023/43226146-9b12a7e2-9020-11e8-9938-500bdd492d9c.png)

![image003](https://user-images.githubusercontent.com/39315023/43226157-a3234982-9020-11e8-83d3-858571bcda02.png)

2) Add error checking such that if an author string with bad data is found,
it skips that author (with an error message) and continues with the rest.

3) Add text when for the search author selection method (on the page or js box(?)
     "Type letter(s) to see matching authors".

**Comment by lauramengel** [comment]
From Eric
> 1) Where would the warning come out? The warning is going to
> come from Javascript, so it’s not so easy to get it back on the page.

Good point. Would it make sense to put it in a JS pop-up alert box?

**Comment by ericvaandering** [comment]
I doubt it. Let's test with some problematic names first and see what makes the most sense.

**Comment by lauramengel** [comment]
Ok. Worst case, we should skip the problematic name and continue showing the rest of the author list.
At the moment it just cuts off the author list to a fixed subset of names or shows no authors, and then users can not create any documents.

**Comment by ericvaandering** [comment]
On the hint text, the author selection already has the link to switch to ordered, so that would get confusing. Do you think it's enough to put a hint on the submitter box? "Type to search" or some such?

This is something I've not heard a complaint about in 10 years on CMS, but I'm willing to try.

**Comment by ericvaandering** [comment]
Actually a bit of text was easy to add:

![screen shot 2018-07-27 at 11 20 34 am](https://user-images.githubusercontent.com/1672366/43332932-37e20d50-918f-11e8-91e1-24cade267fe6.png)

**Comment by ericvaandering** [comment]
I was confused because today it's impossible to insert an author without a first and last name. However, sometime around 10 years ago, this was possible. So FNAL for Mini Boone must date to a version of DocDB which is that old. 

Today, I get "FNAL, " in the author list if I insert with a first name of [space]. And then things work fine. 

I replicated this problem by removing the protection and then inserting a name without even a space as a first name.

**Comment by ericvaandering** [comment]
@lauramengel I have a patch for this in #95. I wasn't happy with Muhammed's suggestion because it always matched FNAL no matter what was typed. This seems to behave basically how I want. You can test it on the original SSO DocDB we set up.

But my JS is barely literate, so if Muhammed has a minute to look at it, I'd appreciate it.

Also I noticed that search results order puts interior last name matches before start-of first name matches. I don't know what you think about changing that.

![screen shot 2018-07-27 at 3 07 11 pm](https://user-images.githubusercontent.com/1672366/43344358-08e31704-91af-11e8-868d-6d1df576bded.png)
